### ISSUE TITLE
Implement speaker-recognition to alexylem/jarvis project

### ISSUE THREAD

**Issue by wikijm** [Adirockzz95/Piwho#2]
Hi everyone,

I'd like to know if your team could help us to integrate your solution to Jarvis, which is a lightweight configurable multi-lang jarvis-like bot, meant for home automation running on slow computer.

More information here: https://github.com/alexylem/jarvis
Even if it's creator is French, the project is most of the time carried in English.

We would like to implement your solution to adapt commands regarding to the requester.
Ex: Read a personal music playlist
=> If John say: "Play some music", Jarvis answer "OK, let's play some rock!"
=> If Jane say: "Play some music", Jarvis answer "OK, let's play some pop."

Thanks in advance 😄

**Comment by Adirockzz95** [comment]
You can use the [same process](https://github.com/Adirockzz95/Piwho/blob/master/docs/jasper.rst) if the JARVIS's architecture is same as JASPER's. The recognition is done on 'Active' part of the conversation.
```
User:   Jarvis
Jarvis: Yes?
User:   Do X thing
 ```
Audio containing 'Do X thing' would be extracted for recognition.

**Comment by wikijm** [comment]
Thanks for the track, we will try to follow it 😃
