### ISSUE TITLE
Speaker scores

### ISSUE THREAD

**Issue by Strumwulf** [Adirockzz95/Piwho#5]
Is there a way using get_speaker_scores() to get the score for a single name?

**Comment by Adirockzz95** [comment]
get_speaker_scores() returns a dictionary of speaker name and its corresponding score. If you want specific score just convert it into a list:
```python
 res = {'A':1, 'B':2, 'C':3}
 spkr = list(res.items())
 print(spkr[1]) # would print ('B', 2)
```

**Comment by Strumwulf** [comment]
Thank you for the information.
