### ISSUE TITLE
name list is returning as "None"

### ISSUE THREAD

**Issue by bstroner** [Adirockzz95/Piwho#8]
Hello,

I have successfully trained and have a .gzbin file and speakers.txt. When I try to return the name list from recog.identify_speaker() like so:
```
name = []
vad.record()
name = recog.identify_speaker()
print(name)
```
name does not contain anything. Is there something I am missing? Thanks

**Comment by Adirockzz95** [comment]
Put ``recog.debug = True`` after ``vad.record()``  it will print error log.

**Comment by sudhashuallurwar** [comment]
<b>JUST FOR INFORMATION</b>
<pre><code>
<i>if not self.debug:</i>       
               try:
                    names = []
                    names.append(str((name[2].split()[2]).decode('utf-8')))
                    names.append(str((name[3].split()[3]).decode('utf-8')))
                    <b>return names</b>
                except IndexError:
                    logging.error('MARF execution failed.'
                                  ' Please set debug=True to print error'
                                  ' info.', exc_info=True)

            else:
                # sanitize string
                data = (''.join(str(x) for x in name))
                fi = data.encode('ascii', 'ignore').decode('unicode_escape')
                print(re.sub("[b']", '', fi)) </code></pre>
In condition you have used <b>'if not self.debug'</b>. In case you turn on the debug flag you will never get names, so turn off the debug flag after solving the issue.
